YAPP-admin/attendance-android

.github/PULL_REQUEST_TEMPLATE.md
app/build.gradle
app/google-services.json
app/proguard-rules.pro
build.gradle

Implement Firebase Setting and Fix PR Template
**Check List**

Implement Firebase Setting and Fix PR Template

---

common/src/main/java/com/yapp/common/base/BaseViewModel.kt
presentation/src/main/java/com/yapp/presentation/ui/login/state/QRMainContract.kt
presentation/src/main/java/com/yapp/presentation/ui/member/main/QRMainViewModel.kt
presentation/src/main/java/com/yapp/presentation/ui/member/main/screen/QRMain.kt

- sideeffect, event, state 개념 확립 및 baseViewModel 수정
**Check List**

Provide `dispatchEvent` in BaseViewModel

---

app/src/main/java/com/yapp/attendance/di/FirebaseModule.kt
common/build.gradle.kts
common/src/main/java/com/yapp/common/util/FirebaseRemoteConfigProvider.kt
data/build.gradle.kts
data/src/main/java/com/yapp/data/firebase/FirebaseRemoteConfigProvider.kt
domain/src/main/java/com/yapp/domain/util/firebase/FirebaseRemoteConfig.kt
domain/src/main/java/com/yapp/domain/util/firebase/RemoteConfigData.kt
presentation/src/main/java/com/yapp/presentation/ui/member/main/QRMainViewModel.kt

Firebase RemoteConfig 셋팅 위치를 common 에서 domain/data 로 분리
뷰모델에서 interface 를 주입받을 수 있도록 변경 
**Check List**

Fix Firebase Remote Config Setting

---

common/src/main/java/com/yapp/common/yds/YDSAppBar.kt
common/src/main/java/com/yapp/common/yds/YDSDropDownButton.kt
common/src/main/java/com/yapp/common/yds/YDSPopupDialog.kt
common/src/main/res/drawable/ic_arrow_back.xml
presentation/src/main/java/com/yapp/presentation/ui/member/main/QRMain.kt

디자인 스펙에 맞게 컴포넌트 변경
**Check List**

디자인 스펙에 맞게 컴포넌트 변경

---

README.md
app/src/main/AndroidManifest.xml
app/src/main/java/com/yapp/attendance/App.kt
presentation/src/main/java/com/yapp/presentation/model/SessionModel.kt
presentation/src/main/java/com/yapp/presentation/ui/AttendanceScreen.kt
presentation/src/main/java/com/yapp/presentation/ui/MainActivity.kt
presentation/src/main/java/com/yapp/presentation/ui/admin/main/AdminMain.kt
presentation/src/main/java/com/yapp/presentation/ui/admin/main/AdminMainContract.kt
presentation/src/main/java/com/yapp/presentation/ui/admin/main/AdminMainViewModel.kt
presentation/src/main/java/com/yapp/presentation/ui/member/detail/MemberScore.kt
presentation/src/main/java/com/yapp/presentation/ui/member/detail/MemberScoreContract.kt
presentation/src/main/java/com/yapp/presentation/ui/member/detail/MemberScoreViewModel.kt
presentation/src/main/java/com/yapp/presentation/ui/splash/Splash.kt
presentation/src/main/java/com/yapp/presentation/ui/splash/SplashActivity.kt

- 스플래시 코드만 추가
- 패키지 정리
**Check List**

Implement Splash Screen

---

presentation/src/main/java/com/yapp/presentation/model/type/PlatformType.kt
presentation/src/main/java/com/yapp/presentation/ui/AttendanceScreen.kt
presentation/src/main/java/com/yapp/presentation/ui/member/signup/Team.kt

팀 선택 화면에서 팀 선택 버튼 클릭 시 크래시 수정
**Check List**

팀 선택 시 크래시 수정

---

app/build.gradle.kts
build.gradle.kts
buildSrc/src/main/java/com/yapp/buildsrc/Configs.kt
buildSrc/src/main/java/com/yapp/buildsrc/Dependencies.kt
presentation/build.gradle.kts
presentation/src/main/java/com/yapp/presentation/ui/AttendanceScreen.kt
presentation/src/main/java/com/yapp/presentation/ui/MainActivity.kt
presentation/src/main/java/com/yapp/presentation/ui/login/Login.kt
presentation/src/main/java/com/yapp/presentation/ui/login/LoginContract.kt
presentation/src/main/java/com/yapp/presentation/ui/login/LoginViewModel.kt
presentation/src/main/java/com/yapp/presentation/ui/member/setting/MemberSetting.kt
presentation/src/main/java/com/yapp/presentation/ui/member/setting/MemberSettingContract.kt
presentation/src/main/java/com/yapp/presentation/ui/member/setting/MemberSettingViewModel.kt
presentation/src/main/java/com/yapp/presentation/ui/splash/SplashViewModel.kt

- 크래시틱스 추가
- 카카오 로그인, 로그아웃 기능 추가 및 개선
- 네비게이션 백스택 수정 
**Check List**

크래시틱스 추가 및 카카오 로그인, 로그아웃 작업 

---

common/src/main/java/com/yapp/common/yds/YDSAppBar.kt
common/src/main/java/com/yapp/common/yds/YDSAttendanceList.kt
presentation/src/main/java/com/yapp/presentation/model/Session.kt
presentation/src/main/java/com/yapp/presentation/ui/AttendanceScreen.kt
presentation/src/main/java/com/yapp/presentation/ui/member/main/MemberMain.kt
presentation/src/main/java/com/yapp/presentation/ui/member/score/MemberScore.kt
presentation/src/main/java/com/yapp/presentation/ui/member/score/MemberScoreContract.kt
presentation/src/main/java/com/yapp/presentation/ui/member/score/MemberScoreViewModel.kt
presentation/src/main/java/com/yapp/presentation/ui/member/score/detail/SessionDetail.kt
presentation/src/main/java/com/yapp/presentation/ui/member/score/detail/SessionDetailNavParam.kt
presentation/src/main/java/com/yapp/presentation/ui/member/todaysession/TodaySession.kt

- 출결 점수 확인 상세화면 구현 
- YDSAppBar 디자인 변경 
**Check List**

출결 점수 확인 상세화면 구현 

---

data/src/main/java/com/yapp/data/model/SessionModel.kt
data/src/main/java/com/yapp/data/model/TeamModel.kt
domain/src/main/java/com/yapp/domain/model/SessionEntity.kt
domain/src/main/java/com/yapp/domain/model/TeamEntity.kt
presentation/src/main/java/com/yapp/presentation/model/Session.kt
presentation/src/main/java/com/yapp/presentation/model/Team.kt
presentation/src/main/java/com/yapp/presentation/model/type/TeamType.kt
presentation/src/main/java/com/yapp/presentation/ui/member/signup/Team.kt
presentation/src/main/java/com/yapp/presentation/ui/member/signup/TeamViewModel.kt

- Session에서 isOff필드가 추가 됐습니다
- Team에서 애매한 필드 이름을 변경했습니다
**Check List**

Fix: Model부분 개선

---

data/src/main/java/com/yapp/data/model/types/PositionTypeModel.kt
domain/src/main/java/com/yapp/domain/model/types/PositionTypeEntity.kt
presentation/src/main/java/com/yapp/presentation/model/type/PositionType.kt

- FrontEnd로 돼있던 Position을 세분화 합니다 
- DEV_ANDROID
- DEV_WEB
- DEV_SERVER
- DEV_IOS
- DESIGNER
- PROJECT_MANAGER
**Check List**

Fix: Position Type 더 세분화

---

data/src/main/java/com/yapp/data/model/AttendanceModel.kt
domain/src/main/java/com/yapp/domain/model/AttendanceEntity.kt
presentation/src/main/java/com/yapp/presentation/model/Attendance.kt

- 미통보 / 통보의 개념이 없어지고 결석 / 지각 / 출석 / 출석인정 
4가지 타입으로 기획이 변경됨
**Check List**

Fix: AttendanceType 기획 변경에 따른 수정

---

app/src/main/AndroidManifest.xml
presentation/src/main/java/com/yapp/presentation/ui/AttendanceScreen.kt
presentation/src/main/java/com/yapp/presentation/ui/member/privacy_policy/PrivacyPolicyScreen.kt
presentation/src/main/java/com/yapp/presentation/ui/member/setting/MemberSetting.kt
presentation/src/main/java/com/yapp/presentation/ui/member/setting/MemberSettingContract.kt
presentation/src/main/java/com/yapp/presentation/ui/member/setting/MemberSettingViewModel.kt

- 개인정보 처리방침을 구현합니다
https://user-images.githubusercontent.com/53253298/161955733-d604596e-185a-4519-b020-c9ab5364904d.mp4
**Check List**

feat: 개인정보 처리방침 구현

---

common/src/main/java/com/yapp/common/theme/Type.kt

SemiBold가 안들어가고 있음을 확인하고 수정합니다
**Check List**

FIX: 타이포그라피 수정

---

presentation/src/main/java/com/yapp/presentation/model/type/TeamType.kt

TeamType을 만드는 of메서드의 표준 String값이 예전 값으로 되어있어 수정합니다
**Check List**

fix: TeamType 생성자 메서드 수정 

---

common/src/main/java/com/yapp/common/base/BaseViewModel.kt
presentation/src/main/java/com/yapp/presentation/ui/MainViewModel.kt
presentation/src/main/java/com/yapp/presentation/ui/admin/browse/AdminTotalScoreViewModel.kt
presentation/src/main/java/com/yapp/presentation/ui/admin/main/AdminMainViewModel.kt
presentation/src/main/java/com/yapp/presentation/ui/login/LoginViewModel.kt
presentation/src/main/java/com/yapp/presentation/ui/member/main/MemberMainViewModel.kt
presentation/src/main/java/com/yapp/presentation/ui/member/qrcodescanner/QrCodeViewModel.kt
presentation/src/main/java/com/yapp/presentation/ui/member/score/MemberScoreViewModel.kt
presentation/src/main/java/com/yapp/presentation/ui/member/setting/MemberSettingViewModel.kt
presentation/src/main/java/com/yapp/presentation/ui/member/signup/name/NameViewModel.kt
presentation/src/main/java/com/yapp/presentation/ui/member/signup/position/PositionViewModel.kt
presentation/src/main/java/com/yapp/presentation/ui/member/signup/team/TeamViewModel.kt
presentation/src/main/java/com/yapp/presentation/ui/splash/SplashViewModel.kt

- handleEvent가 suspend funtion로 수정하여 매번 CoroutineScope를 열어줘야 하는 문제를 해결합니다
**Check List**

fix: BaseViewModel의 handleEvent를 suspend로 변경

---

presentation/src/main/java/com/yapp/presentation/ui/member/signup/team/Team.kt

- 회원 가입 Team Select시 크래시 발생 현상을 수정합니다.
- 클릭시 해당 Type의 displayName("Android")이 아닌 name("ANDROID")가 와야함
**Check List**

Fix: 팀 선택시 크래시 발생현상 수정

---

domain/src/main/java/com/yapp/domain/util/DateUtil.kt

- isUpcomingSession 오류 수정
**Check List**

upcoming 세션 체크 오류 수정

---

domain/src/main/java/com/yapp/domain/util/DateUtil.kt

- isUpcomingSession 오류 수정
- time으로 비교할 때 값이 예상과 다르게 나와서 string끼리 비교하도록 수정
**Check List**

upcoming 세션 오류 수정

---

common/src/main/java/com/yapp/common/util/KakaoSdkProvider.kt
data/src/main/java/com/yapp/data/repository/LocalRepositoryImpl.kt
data/src/main/java/com/yapp/data/repository/MemberRepositoryImpl.kt
domain/src/main/java/com/yapp/domain/common/KakaoSdkProviderInterface.kt
domain/src/main/java/com/yapp/domain/repository/LocalRepository.kt
domain/src/main/java/com/yapp/domain/repository/MemberRepository.kt
domain/src/main/java/com/yapp/domain/usecases/DeleteMemberInfoUseCase.kt
domain/src/main/java/com/yapp/domain/usecases/GetMemberIdUseCase.kt
presentation/src/main/java/com/yapp/presentation/ui/AttendanceScreen.kt
presentation/src/main/java/com/yapp/presentation/ui/login/LoginViewModel.kt
presentation/src/main/java/com/yapp/presentation/ui/member/setting/MemberSetting.kt
presentation/src/main/java/com/yapp/presentation/ui/member/setting/MemberSettingContract.kt
presentation/src/main/java/com/yapp/presentation/ui/member/setting/MemberSettingViewModel.kt
presentation/src/main/java/com/yapp/presentation/ui/splash/SplashViewModel.kt

로그인, 회원탈퇴 로직 수정 
**Check List**

로그인, 회원탈퇴 로직 수정 

---

presentation/src/main/java/com/yapp/presentation/ui/member/todaysession/TodaySession.kt

- 오늘의 세션 화면에서 모든 세션을 마친 경우(session = null) '모든 세션을 끝마쳤습니다' 메시지를 표시합니다.
**Check List**

오늘의 세션 화면 모든 세션 마친 경우 메시지 표시

---

presentation/src/main/java/com/yapp/presentation/ui/member/score/MemberScore.kt
presentation/src/main/java/com/yapp/presentation/ui/member/score/MemberScoreContract.kt
presentation/src/main/java/com/yapp/presentation/ui/member/score/MemberScoreViewModel.kt
presentation/src/main/java/com/yapp/presentation/ui/member/signup/team/TeamViewModel.kt

- 그래프 반원에 점수 넣기
- 출석, 지각, 결석 수 세기 (출석은 출석체크하는 세션만 셉니다!)
| <img width="289" alt="image" src="https://user-images.githubusercontent.com/67185391/164882503-bfb7b015-507d-4c24-99fd-0b84217c9a08.png">  |             |
**Check List**

출결 확인 그래프 및 표 그리기

---

app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml

- anydpi-v26 런쳐 아이콘 리소스 제거
**Check List**

런쳐 아이콘 not found 오류 해결

---

presentation/src/main/java/com/yapp/presentation/ui/admin/management/ManagementViewModel.kt

fix: 기존 멤버의 출결을 수정할때 항상 0번 세션을 가져오는 오류 수정

---

presentation/src/main/java/com/yapp/presentation/ui/AttendanceScreen.kt
presentation/src/main/java/com/yapp/presentation/ui/member/setting/MemberSetting.kt

- 관리자 전환 버튼 삭제
- 타이포그래피 적용
| <img width="510" alt="스크린샷 2022-05-06 오후 4 26 05" src="https://user-images.githubusercontent.com/42907876/167086569-85a61b78-06cd-460c-9414-7054f1cc6587.png"> |             |
**Check List**

설정 화면을 수정합니다

---

presentation/src/main/java/com/yapp/presentation/ui/member/score/MemberScore.kt

출석점수가 음수인 경우 그래프가 바깥으로 그려지는 버그 수정!
**Check List**

출석점수가 음수인 경우 그래프가 바깥으로 그려지는 버그

---

common/src/main/java/com/yapp/common/yds/YDSButtons.kt
presentation/src/main/java/com/yapp/presentation/ui/admin/main/AdminMain.kt
presentation/src/main/java/com/yapp/presentation/ui/admin/management/Management.kt

#158 에 해당하는 이슈를 해결합니다
|     ![스크린샷 2022-06-01 오후 6 08 25](https://user-images.githubusercontent.com/53253298/171369307-3b00c61a-735a-4d51-917f-6c4dd95ce7da.png)        |       ![스크린샷 2022-06-01 오후 6 08 47](https://user-images.githubusercontent.com/53253298/171369374-f5cfbc19-99ef-4b49-9d02-71b85a2236a5.png)      |
**Check List**

Fix: 출결관리 화면 UI이슈 해결

---

common/src/main/java/com/yapp/common/yds/YDSButtons.kt
presentation/src/main/java/com/yapp/presentation/ui/member/score/MemberScore.kt
presentation/src/main/java/com/yapp/presentation/ui/member/signup/position/Position.kt
presentation/src/main/java/com/yapp/presentation/ui/member/signup/team/Team.kt
presentation/src/main/res/values/strings.xml

#151 
#154 
#155 
해당 이슈들을 해결합니다.
|  ![Screenshot_20220605-154616_attendance-android](https://user-images.githubusercontent.com/53253298/172039024-96ea5582-60e3-418d-9f5f-fddb83de4ad8.jpg)  |     ![Screenshot_20220605-154624_attendance-android](https://user-images.githubusercontent.com/53253298/172039039-a5f73988-3336-4bce-8daa-ef327ec1d4b1.jpg)        |
**Check List**

Fix: SignUp화면 디자인 이슈, 출석점수 확인 화면 이슈 수정

---

presentation/src/main/java/com/yapp/presentation/ui/login/LoginViewModel.kt

로그인 성공 후 회원가입 화면으로 이동할 때 로그인 성공 토스트를 제거합니다.
**Check List**

로그인 후 회원가입 할 때 로그인 성공 토스트 제거

---

presentation/src/main/java/com/yapp/presentation/ui/login/Login.kt

- 로그인 화면 건너뛰기 버튼 제거
**Check List**

로그인 건너뛰기 버튼 제거

---

common/src/main/java/com/yapp/common/util/KeyboardVisibilityUtils.kt
presentation/src/main/java/com/yapp/presentation/ui/AttendanceScreen.kt

- 뒤로가기 버튼을 눌렀을 때 로그인 화면으로 이동하며 백스택을 삭제합니다.
- 키보드를 눌렀을 때 버튼이 바뀌지 않는 오류를 수정합니다.
**Check List**

이름 작성 화면의 버그를 고칩니다.

---

app/src/main/AndroidManifest.xml

fix: "kakao"와 네이티브 API키를 분리

---

data/src/main/java/com/yapp/data/firebase/FirebaseRemoteConfigProvider.kt
domain/src/main/java/com/yapp/domain/firebase/FirebaseRemoteConfig.kt
domain/src/main/java/com/yapp/domain/firebase/RemoteConfigData.kt
domain/src/main/java/com/yapp/domain/usecases/ShouldShowGuestButtonUseCase.kt
presentation/src/main/java/com/yapp/presentation/ui/login/Login.kt
presentation/src/main/java/com/yapp/presentation/ui/login/LoginContract.kt
presentation/src/main/java/com/yapp/presentation/ui/login/LoginViewModel.kt
presentation/src/main/java/com/yapp/presentation/ui/member/setting/MemberSettingContract.kt
presentation/src/main/java/com/yapp/presentation/ui/member/setting/MemberSettingViewModel.kt
presentation/src/main/java/com/yapp/presentation/ui/member/signup/team/TeamContract.kt

guest button 등장~~~~~~
**Check List**

플레이스토어 심사용 계정 및 플로우 생성

---

presentation/src/main/java/com/yapp/presentation/ui/login/Login.kt
presentation/src/main/java/com/yapp/presentation/ui/login/LoginViewModel.kt

게스트 로그인 버튼 visibility 설정

---

README.md

20기 / 21기 출석체크앱 프로젝트에 참여한 인원들을 추가합니다.
**Check List**

fix: Readme에 Contributors 추가

---

.github/auto_assign.yml

- 깃허브 Auto Assigned 를 수정했어요
- 기본 리뷰어를 1명에서 3명으로 변경했어요
**Check List**

[ Refactor ] auto assign.yml 수정

---

buildSrc/src/main/java/com/yapp/buildsrc/Configs.kt

chore: Version Up (1.0.2 -> 1.1.0) 🔥🔥🔥

---

data/src/main/java/com/yapp/data/datasource/MemberRemoteDataSourceImpl.kt

- `callbackFlow` 구독 상황이 아니면 리스너를 `null` 처리하도록 수정하였습니다.
- `null` 처리를 하지 않으면 `callbackFlow` 를 구독하던 화면에서 빠져나가더라도 listener 는 계속해서 동작을 하고, 만약 화면에 여러 번 진입하게 되면 listener 콜백이 여러 번 동작하게 됩니다.
- listener 의 메모리 지속 점유를 막아 메모리 누수를 방지하였습니다.
**Check List**

refactor: callbackFlow 구독 상황이 아니면 리스너를 null 처리하도록 수정

---

data/src/main/java/com/yapp/data/model/TeamEntity.kt
presentation/src/main/java/com/yapp/presentation/ui/admin/management/Management.kt
presentation/src/main/java/com/yapp/presentation/ui/member/signup/position/Position.kt

- #212 해당 PR의  Compose 버전 업데이트 이후 InnerPadding을 넣어야 컴파일이 꺠지지 않았는데
이때, innerPadding을 잘못 넣어줘서 화면이 잘못 표시되는 문제를 해결합니다
- TeamEntity를 valueOf가 아닌 커스텀 메서드인 from으로 매핑하도록 수정합니다.
**Check List**

fix: innerPadding 수정 및 TeamEntity 매핑 이슈 해결
